"""Generate an arXiv-ready paper skeleton and experiment tables."""

from __future__ import annotations

import shutil
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Union

from openscholarguard.benchmark.datasets import get_builtin_dataset
from openscholarguard.benchmark.evaluator import evaluate_builtin_dataset
from openscholarguard.benchmark.models import BenchmarkEvaluation
from openscholarguard.benchmark.submissions import load_benchmark_evaluation
from openscholarguard.models import Severity


@dataclass(frozen=True)
class PaperArtifacts:
    """Paths written by the paper skeleton generator."""

    output_dir: Path
    main_tex: Path
    dataset_table: Path
    results_table: Path
    readme: Path
    evaluation_json: Path


def generate_paper_skeleton(
    output_dir: Union[str, Path],
    *,
    dataset: str = "scholarguardbench-v0",
    evaluation: Optional[BenchmarkEvaluation] = None,
    evaluation_path: Optional[Union[str, Path]] = None,
    overwrite: bool = False,
) -> PaperArtifacts:
    """Generate a LaTeX paper skeleton and benchmark tables."""

    output_path = Path(output_dir).expanduser()
    if output_path.exists() and any(output_path.iterdir()):
        if not overwrite:
            raise ValueError(f"Paper output directory already exists and is not empty: {output_path}")
        shutil.rmtree(output_path)
    output_path.mkdir(parents=True, exist_ok=True)
    tables_dir = output_path / "tables"
    artifacts_dir = output_path / "artifacts"
    tables_dir.mkdir(parents=True, exist_ok=True)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    if evaluation is None and evaluation_path is not None:
        evaluation = load_benchmark_evaluation(evaluation_path)
    if evaluation is None:
        evaluation = evaluate_builtin_dataset(
            dataset,
            fail_on=Severity.HIGH,
            work_dir=artifacts_dir / "generated-samples",
        )

    dataset_obj = get_builtin_dataset(evaluation.dataset)
    evaluation_json = artifacts_dir / "evaluation.json"
    evaluation_json.write_text(evaluation.to_json(), encoding="utf-8")

    dataset_table = tables_dir / "dataset_coverage.tex"
    results_table = tables_dir / "deterministic_baseline.tex"
    main_tex = output_path / "main.tex"
    readme = output_path / "README.md"

    dataset_table.write_text(_dataset_table(dataset_obj), encoding="utf-8")
    results_table.write_text(_results_table(evaluation), encoding="utf-8")
    main_tex.write_text(_main_tex(evaluation), encoding="utf-8")
    readme.write_text(_paper_readme(evaluation), encoding="utf-8")

    return PaperArtifacts(
        output_dir=output_path,
        main_tex=main_tex,
        dataset_table=dataset_table,
        results_table=results_table,
        readme=readme,
        evaluation_json=evaluation_json,
    )


def _dataset_table(dataset: object) -> str:
    from openscholarguard.benchmark.models import BenchmarkDataset

    if not isinstance(dataset, BenchmarkDataset):
        raise TypeError("dataset table requires a BenchmarkDataset")
    counts = Counter(case.family.value for case in dataset.cases)
    lines = [
        "% Auto-generated by openscholarguard paper.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Attack family & Cases \\\\",
        "\\midrule",
    ]
    for family, count in sorted(counts.items()):
        lines.append(f"{_latex_escape(family.replace('_', ' '))} & {count} \\\\")
    lines.extend(
        [
            "\\midrule",
            f"Total & {len(dataset.cases)} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\caption{Coverage of the synthetic ScholarGuardBench seed dataset.}",
            "\\label{tab:dataset-coverage}",
            "\\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


def _results_table(evaluation: BenchmarkEvaluation) -> str:
    metrics = evaluation.metrics
    lines = [
        "% Auto-generated by openscholarguard paper.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "System & Accuracy & Precision & Recall & F1 & Detector recall \\\\",
        "\\midrule",
        (
            "OpenScholarGuard deterministic scanner & "
            f"{metrics.accuracy:.4f} & {metrics.precision:.4f} & {metrics.recall:.4f} & "
            f"{metrics.f1:.4f} & {metrics.detector_recall:.4f} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Initial deterministic baseline on the built-in benchmark.}",
        "\\label{tab:deterministic-baseline}",
        "\\end{table}",
        "",
    ]
    return "\n".join(lines)


def _main_tex(evaluation: BenchmarkEvaluation) -> str:
    return f"""% Auto-generated OpenScholarGuard arXiv skeleton.
\\documentclass[11pt]{{article}}
\\usepackage[margin=1in]{{geometry}}
\\usepackage{{booktabs}}
\\usepackage{{hyperref}}
\\usepackage{{xcolor}}

\\title{{OpenScholarGuard: Securing AI-Assisted Scholarly Review Against Document-Borne Prompt Injection}}
\\author{{OpenScholarGuard Contributors}}
\\date{{}}

\\begin{{document}}
\\maketitle

\\begin{{abstract}}
AI-assisted peer review and document agents increasingly ingest PDFs, metadata, OCR layers,
figures, and retrieved context. This creates a new attack surface: scholarly documents can
carry model-facing instructions that are invisible or irrelevant to human reviewers. We
present OpenScholarGuard, an open-source security and trust layer for scanning, sanitizing,
and benchmarking document-borne prompt-injection risks in AI science workflows.
\\end{{abstract}}

\\section{{Introduction}}
Motivate the need for document-native safety infrastructure for AI reviewers, AI scientists,
and RAG systems. Emphasize that the document itself is an untrusted input channel.

\\section{{Threat Model}}
Define document-borne prompt injection across visible text, hidden markup, PDF metadata,
OCR layers, images, Unicode obfuscation, citation manipulation, and RAG contamination.

\\section{{System}}
Describe the scanner, sanitizer, guarded ingestion pipeline, rule-pack verification,
optional LLM audit, static demo, and benchmark publication workflow.

\\section{{ScholarGuardBench}}
Describe the synthetic benchmark seed, metadata schema, attack families, expected detectors,
and response/judge protocol for future model-facing evaluations.

\\input{{tables/dataset_coverage}}

\\section{{Experiments}}
Report deterministic scanner results on \\texttt{{{_latex_escape(evaluation.dataset)}}}
version \\texttt{{{_latex_escape(evaluation.version)}}}. Add model-run and LLM-judge results as
the benchmark grows.

\\input{{tables/deterministic_baseline}}

\\section{{Limitations}}
Discuss synthetic data, heuristic detectors, OCR availability, PDF rendering differences,
and the need for external validation with publisher and conference workflows.

\\section{{Ethics and Responsible Release}}
Explain why examples are synthetic, how hidden instructions are handled safely, and how
benchmark submissions should avoid leaking private reviews or unpublished papers.

\\section{{Conclusion}}
OpenScholarGuard turns document safety for AI science workflows into a reproducible
engineering surface: scan, sanitize, evaluate, and publish.

\\bibliographystyle{{plain}}
\\bibliography{{references}}

\\end{{document}}
"""


def _paper_readme(evaluation: BenchmarkEvaluation) -> str:
    return f"""# OpenScholarGuard Paper Skeleton

This directory was generated by:

```bash
openscholarguard paper --output-dir paper-output --dataset {evaluation.dataset}
```

Files:

- `main.tex`: arXiv-style paper skeleton.
- `tables/dataset_coverage.tex`: generated benchmark coverage table.
- `tables/deterministic_baseline.tex`: generated baseline metrics table.
- `artifacts/evaluation.json`: machine-readable benchmark evaluation used by the tables.

Compile with a LaTeX environment that provides `booktabs` and `hyperref`.
"""


def _latex_escape(value: str) -> str:
    replacements = {
        "\\": "\\textbackslash{}",
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
        "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)
